version: '3.9'

services:
  test-app:
    container_name: test-sangeet-container
    image: test-sangeet-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.test
    ports:
      - '${EXPOSE_PORT}:${APP_PORT}'
    depends_on:
      - test-sangeet-postgres
    command: yarn start:dev
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  test-sangeet-postgres:
    container_name: test-sangeet-database
    image: postgres:15-alpine
    ports:
      - $POSTGRES_PORT:5432
    env_file:
      - .env.test
