### Create a new user
POST http://localhost:1337/artist-managers/signup
Content-Type: application/json

{
  "email": "duper@pm.me",
  "username": "super123",
  "password": "password123"
}

### Signin
POST http://localhost:1337/artist-managers/signin
Content-Type: application/json

{
  "email": "duper@pm.me",
  "password": "password123"
}

### Signout
POST http://localhost:1337/artist-managers/signout

### Who am I
GET http://localhost:1337/artist-managers/whoami

### Get requests (has to be admin)
GET http://localhost:1337/artist-managers/requests

### Request for verification
GET http://localhost:1337/artist-managers/request-for-verification
Content-Type: application/json

{
  "letter": "Please acccept me"
}